[versions]
configurate = "4.1.2"

[libraries]
configurate = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }

[bundles]
configurate = [ "configurate", "configurate-yaml" ]